package com.substring.chat.entities;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Message {

    private String sender; // The sender of the message
    private String content; // The content of the message
    private LocalDateTime timestamp; // The timestamp when the message was sent

    public void setContent(String content) {
        this.content = content;
    }

    public void setSender(String sender) {
        this.sender = sender;
    }

    public void setTimestamp(LocalDateTime now) {
        this.timestamp = timestamp;
    }

    // You don't need to manually write the no-argument constructor because Lombok's @NoArgsConstructor does this for you.

    // Constructor with sender, content, and timestamp (this one is auto-generated by Lombok)
    // The @AllArgsConstructor annotation will create a constructor with all fields.

    // Getter and Setter methods are generated by Lombok's @Getter and @Setter annotations
}
